import { StyleSheet } from 'react-native-unistyles'

export const styles = StyleSheet.create((theme, rt) => ({
  root: { flex: 1, backgroundColor: theme.colors.cameraBackground },
  flashOverlay: { backgroundColor: theme.colors.flashEffect, zIndex: 10 },
  topBar: {
    position: 'absolute',
    top: rt.insets.top + 12,
    left: 0,
    right: 0,
    zIndex: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.xl,
  },
  topBarRight: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  iconBtn: {
    // 48x48dp — Android Material touch-target minimum (ux_principles.md #1);
    // 44 (iOS HIG minimum) was under it on Android.
    width: 48,
    height: 48,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 25,
  },
  pill: {
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 10,
    borderRadius: 24,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 25,
  },
  pillText: { color: theme.colors.text, fontSize: 15, fontWeight: '600' },
  autoA: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    color: theme.colors.text,
    fontSize: 10,
    fontWeight: '800',
  },
  bottomBar: {
    position: 'absolute',
    // Mirrors topBar's `rt.insets.top + 12` — the shutter row was flush
    // against the raw screen edge with no safe-area/gesture-nav clearance.
    bottom: rt.insets.bottom + theme.spacing.lg,
    left: 0,
    right: 0,
    zIndex: 20,
  },
  strip: { height: 64 + 16, marginBottom: theme.spacing.xl },
  shutterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 44,
  },
  sideBtn: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sideBtnFilled: {
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
    zIndex: 25,
  },
  shutter: {
    width: 78,
    height: 78,
    borderRadius: theme.radius.full,
    borderWidth: 3,
    borderColor: theme.colors.text,
    backgroundColor: theme.colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 25,
  },
  shutterBusy: { opacity: 0.5 },
  shutterInner: {
    width: 64,
    height: 64,
    borderRadius: theme.radius.full,
    backgroundColor: theme.colors.text,
  },
  gate: {
    flex: 1,
    backgroundColor: theme.colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing.xxxl,
    gap: theme.spacing.lg,
  },
  gateTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.xl,
    fontWeight: '700',
    textAlign: 'center',
  },
  gateBody: {
    color: theme.colors.muted,
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  gatePrimary: {
    backgroundColor: theme.colors.accent,
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: theme.spacing.xxxl,
    width: '100%',
    alignItems: 'center',
    marginTop: theme.spacing.sm,
  },
  gatePrimaryText: {
    color: theme.colors.accentText,
    fontSize: 15,
    fontWeight: '600',
  },
  gateSecondary: {
    backgroundColor: theme.colors.surfaceAlt,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.border,
    paddingVertical: 14,
    paddingHorizontal: theme.spacing.xxxl,
    width: '100%',
    alignItems: 'center',
  },
  gateSecondaryText: {
    color: theme.colors.text,
    fontSize: 15,
    fontWeight: '600',
  },
}))
