plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.nativeidentificationcamera'
version = '1.0.0'

android {
  namespace 'expo.modules.nativeidentificationcamera'
}

dependencies {
  implementation 'androidx.camera:camera-core:1.6.2'
  implementation 'androidx.camera:camera-lifecycle:1.6.2'
  implementation 'androidx.camera:camera-view:1.6.2'
}
